language: node_js
node_js:
  - 14

services:
  - docker

install:
  - echo "nothing to install"

before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t steidinger/udagram-api-feed ./udagram-api-feed/
  - docker build -t steidinger/udagram-api-users ./udagram-api-users/
  - docker build -t steidinger/udagram-frontend ./udagram-frontend
  - docker build -t steidinger/udagram-reverse-proxy ./reverse-proxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push steidinger/udagram-api-feed
  - docker push steidinger/udagram-api-users
  - docker push steidinger/udagram-frontend
  - docker push steidinger/udagram-reverse-proxy
