apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverse-proxy
  name: udagram-reverse-proxy-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      # nodePort: 30080
  selector:
    service: udagram-reverse-proxy
    