apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-api-users
  name: udagram-api-users-svc
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: udagram-api-users
